name: drawings
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - pip
  - tensorboard>=2.9.0
  - pillow
  - opencv
  - scikit-learn
  - timm
  - fvcore
  - matplotlib
  - seaborn
  - iopath
  - tqdm
  - pip:
     - oyaml
     - dominate
     - ninja
     - ftfy
     - regex
     - protobuf==3.20.*